#!/usr/bin/env python

# TODO this node

"""
PARAMETERS:

PUBLISHES:

SUBSCRIBES:
    prius/center_laser/scan (sensor_msgs/PointCloud): Point cloud data from center laser of the Prius

SERVICES:

"""

import rospy

from sensor_msgs.msg import PointCloud
from std_msgs.msg import Byte
import numpy as np

# ideas taken from https://shareok.org/bitstream/handle/11244/52288/oksd_hobble_HT_2016.pdf?sequence=1&isAllowed=y

def callback(data):
    msg = Byte()
    if len(valid_regions) > 0:
        msg.data = 1
    else:
        msg.data = 0
    pub.publish(msg)


if __name__=="__main__":
    rospy.init_node('obstacles_pointcloud')
    #pub = rospy.Publisher("/is_clear/front_camera/all",Byte,queue_size=1)
    sub = rospy.Subscriber("/prius/center_laser/scan",PointCloud,callback)

    rospy.spin()